In [1]:
import pandas as pd
import os

def load_diamond_data():
    csv_path = os.path.join("diamonds-dataset", "diamonds-train.csv")
    return pd.read_csv(csv_path)

In [2]:
#Carrega os dados de treino e faz feature scaling(depth, table)
import numpy as np
diamond_data = load_diamond_data()
diamond_data["depth"] = (diamond_data["depth"] / 10)
diamond_data["table"] = (diamond_data["table"] / 10)

In [3]:
#dummy coding(cut,color,clarity)
from sklearn.preprocessing import LabelEncoder
diamond_data = load_diamond_data()
diamond_data["depth"] = diamond_data["depth"] / 10
diamond_data["table"] = diamond_data["table"] / 10

enumValues = {"cut": {"Fair":0, "Good":1, "Very Good":2, "Premium":3, "Ideal":4},
              "color": {"J": 0, "I":1, "H":2, "G":3, "F":4, "E":5, "D":6},
              "clarity": {"I1":0, "SI2":1, "SI1":2, "VS2":3, "VS1":4,"VVS2":5, "VVS1":6, "IF":7}}
diamond_data.replace(enumValues, inplace=True)


In [4]:
# Normal Equation

def NormalEquation(X, y):

    transpose = X.T

    mult1 = transpose.dot(X)

    try:
        inverse = np.linalg.inv(mult1)

    except np.linalg.LinAlgError:
        print("Not invertible")
        return np.zeros(1,1)

    else:
        mult2 = (inverse.dot(transpose)).dot(y)
        return mult2


In [5]:
import numpy as np

#function add a first column filled with 1's and delete de last colum
def prepareSet(setToPrepare):
    X = np.array(setToPrepare)

    X = np.delete(X, -1, axis=1)

    X = np.c_[np.ones((len(X), 1)),X]

    y = np.array(setToPrepare["price"])

    return X,y

In [6]:
# #grafico Carat X Price
# import matplotlib.pyplot as plt
# plt.scatter(diamond_data["carat"], diamond_data["price"])
# plt.xlabel("$carat$", fontsize=18)
# plt.ylabel("$price(U$)$", fontsize=18)
# plt.show()

In [7]:
# #grafico Cut X Price
# import matplotlib.pyplot as plt
# plt.scatter(diamond_data["cut"], diamond_data["price"])
# plt.xlabel("$cut$", fontsize=18)
# plt.ylabel("$price$", fontsize=18)
# plt.show()

In [8]:
# #grafico  Color X Price
# import matplotlib.pyplot as plt
# plt.scatter(diamond_data["color"], diamond_data["price"])
# plt.xlabel("$color$", fontsize=18)
# plt.ylabel("$price$", fontsize=18)
# plt.show()

In [9]:
# #grafico Clarity X Price
# import matplotlib.pyplot as plt
# plt.scatter(diamond_data["clarity"], diamond_data["price"])
# plt.xlabel("$clarity$", fontsize=18)
# plt.ylabel("$price$", fontsize=18)
# plt.show()

In [10]:
# #grafico Depth X Price
# import matplotlib.pyplot as plt
# plt.scatter(diamond_data["depth"], diamond_data["price"])
# plt.xlabel("$depth$", fontsize=18)
# plt.ylabel("$price$", fontsize=18)
# plt.show()

In [11]:
# #grafico table X Price
# import matplotlib.pyplot as plt
# plt.scatter(diamond_data["table"], diamond_data["price"])
# plt.xlabel("$table$", fontsize=18)
# plt.ylabel("$price$", fontsize=18)
# plt.show()

In [12]:
# #grafico x X Price
# import matplotlib.pyplot as plt
# plt.scatter(diamond_data["x"], diamond_data["price"])
# plt.xlabel("$x$", fontsize=18)
# plt.ylabel("$price$", fontsize=18)
# plt.show()

In [13]:
# #grafico y X Price
# import matplotlib.pyplot as plt
# plt.scatter(diamond_data["y"], diamond_data["price"])
# plt.xlabel("$y$", fontsize=18)
# plt.ylabel("$price$", fontsize=18)
# plt.show()

In [14]:
# #grafico z X Price
# import matplotlib.pyplot as plt
# plt.scatter(diamond_data["z"], diamond_data["price"])
# plt.xlabel("$z$", fontsize=18)
# plt.ylabel("$price$", fontsize=18)
# plt.show()

In [16]:
# Cross Validation Generation

# PRECISA CHAMAR ISSO ANTES DE CHAMAR A FUNCAO --- 
#                             TRAINING_DATA = prepareSet(diamond_data) 

from sklearn.model_selection import train_test_split, KFold

#essa funcao retorna um gerador de indices
def generate_sets(TRAINING_DATA,type='kfold'):

    # Cross validation using train_test_split
    if (type == 'split'):
       return train_test_split(TRAINING_DATA,test_size=0.2,random_state=0)

    # Cross validation using K-Fold
    # K = 5, Shuffle = true, Seed = 21
    elif (type == 'kfold'):
        kfold_seed = 21

        kfold = KFold(n_splits=5, shuffle=True, random_state=kfold_seed)
        return kfold.split(TRAINING_DATA)
#         for train_index, test_index in kfold.split(X):
#             X_train, X_test = X[train_index], X[test_index]
#             y_train, y_test = y[train_index], y[test_index]
#             print("TRAIN:", X_train.shape, "TEST:", X_test.shape)
#             print("TEST:", y_train.shape, "TEST:", y_test.shape)

## Explicação do uso do generate_sets

In [17]:

# import numpy as np
# from sklearn.model_selection import train_test_split, KFold

# X = np.array([[10, 20], [30, 40], [50, 60], [70, 80], [90, 100], [110, 120], [130, 140], [150, 160], [170, 180], [190, 200]])
# y = np.array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])

# #esse b vai ser um gerador, não precisa passar y pois ele gera somente os indices
# b = generate_sets(X)

# #precisa percorrer ele com 2 indices, um representa o treino, outro o test, 
# # na proxima iteracao ele ja vai estar num agrupamento diferente
# for train_index, test_index in b:
#     x_train = X[train_index]
#     y_train = y[train_index]
#     x_test = X[test_index]
#     y_test = y[test_index]
#     print(x_train, y_train)
#     print(x_test, y_test)
#     print("-----")
    


In [18]:
# #Scikit-Learn Linear Regression using Stochastic Gradient Descent(SGD) for comparisson
# from sklearn.linear_model import SGDRegressor
# sgd_reg = SGDRegressor(max_iter = 100, eta0=0.1)
# sgd_reg.fit(X_train, y_train)
# sgd_reg.intercept_, sgd_reg.coef_


In [19]:
# for train_index, validate_index in generate_sets():
#     X_train, X_test = X[train_index], X[validate_index]
#     y_train, y_test = y[train_index], y[validate_index]
#     print(LinRegBatchGradientDescent(X_train,y_train.reshape(len(y_train),1),100,0.1))

In [20]:
def learning_schedule(t):
    return t0 / (t + t1)
#TODO
#implementation Linear Regression using Stochastick Gradient Descent(SGD)
def LinRegStochasticGradientDescent(TRAIN_SET, TARGET_SET, N_EPOCHS, LEARNING_RATE):
    t0, t1 = 5, 50  # learning schedule hyperparameters
    theta = np.random.randn(len(TRAIN_SET),1)  # random initialization
    for epoch in range(N_EPOCHS):
        for i in range(m):
            random_index = np.random.randint(m)
            xi = TRAIN_SET[random_index:random_index+1]
            yi = TARGET_SET[random_index:random_index+1]
            gradients = 2 * xi.T.dot(xi.dot(theta) - yi)
            #eta = learning_schedule(epoch * m + i)
            #theta = theta - eta * gradients
            theta = theta - LEARNING_RATE * gradients

In [21]:
#implementation Linear Regression using Mini-Batch Gradient Descent
def LinRegMiniGradientDescent(TRAIN_SET, TARGET_SET, N_ITERATION, LEARNING_RATE, SIZE_BATCH):
    np.random.seed(42)
    theta = np.random.randn(10,1) #random initialization
    for iteration in range(N_ITERATIONS):
        shuffle_indices = np.random.permutation(TRAIN_SET.shape[0])
        train_shuffled = TRAIN_SET[shuffled_indices]
        target_shuffled = TARGET_SET[shuffled_indices]
        for i in range(0,TARGET_SET.shape[0], SIZE_BATCH):
            xi = train_shuffled[i:i+SIZE_BATCH]
            yi = target_shuffled[i:i+SIZE_BATCH]
            gradients = 2/SIZE_BATCH * xi.T.dot(xi.dot(theta) - yi)
            theta = theta - LEARNING_RATE * gradients
    return theta

In [22]:
a = np.array([1,2,3,4,5,6,7])
shuffle_indices = np.random.permutation(7)
train_shuffled = a[shuffle_indices]
train_shuffled

array([2, 4, 6, 7, 1, 5, 3])

### duvidas
funcao stochastic, nao entendi o for i in range(m), não era pra fazer so pra 1?
<br>
funcao mini, na hora de calcular o gradiente nao sera mais pra dividir por m, agora e pra dividir por size_batch
<br>
na funcao da professora, tem um x^(i) multiplicando o theta 1 

# ideias de modelos
usando todas as features
<br>
&nbsp;&nbsp;normal
&nbsp;&nbsp;ao quadrado
<br>
tirando as features que nao aparentam influenciar
<br>
&nbsp;&nbsp;normal
&nbsp;&nbsp; ao quadrado




In [27]:
import numpy as np
#Linear Regression using batch gradient descent
#ex n_iterations = 10000, learning_rate = 0.1
def LinRegBatchGradientDescent(TRAIN_SET, TARGET_SET, N_ITERATIONS, LEARNING_RATE):
    theta = np.random.randn(TRAIN_SET.shape[1],1) #random initialization
    m = TRAIN_SET.shape[0]
    for iteration in range(N_ITERATIONS):
        gradients = 2/m * TRAIN_SET.T.dot(TRAIN_SET.dot(theta) - TARGET_SET)
        theta = theta - LEARNING_RATE * gradients
    return theta

# Proximos 4 celulas e pra mostrar que o nosso Lin

In [31]:
##DATA SET PARA testar A FUNCAO DEPOIS
import numpy as np
import numpy.random as rnd

np.random.seed(42)
X = 2 * rnd.rand(100,1)
y = 4 + 3 * X + rnd.randn(100,1)

In [32]:
import numpy.linalg as LA

X_b = np.c_[np.ones((100, 1)), X] # add x0 = 1 to each instance
theta_best = LA.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y)
theta_best

array([[4.21509616],
       [2.77011339]])

In [45]:
from sklearn.linear_model import SGDRegressor

sgd_reg = SGDRegressor(max_iter=1000, penalty=None, eta0=0.1)
sgd_reg.fit(X, y.ravel())
sgd_reg.intercept_, sgd_reg.coef_

(array([4.2183988]), array([2.77639722]))

In [46]:
# print(x1)
print(LinRegBatchGradientDescent(X_b,y,1000,0.1))

[[4.21509616]
 [2.77011339]]
