In [1]:
import pandas as pd
import os


def load_diamond_data():
    csv_path = os.path.join("diamonds-dataset", "diamonds-train.csv")
    return pd.read_csv(csv_path)

In [2]:
#Carrega os dados de treino
diamond_data_train = load_diamond_data()

In [3]:
#Carrega os dados de treino e faz feature scaling(depth, table)
diamond_data_train = load_diamond_data()
import numpy as np
diamond_data = load_diamond_data()
diamond_data["depth"] = (diamond_data["depth"] / 10)
diamond_data["table"] = (diamond_data["table"] / 10)

In [4]:
diamond_data

carat        cut color clarity     x     y     z  depth  table  price
0       1.62      Ideal     I     VS2  7.53  7.58  4.69   6.21   5.50  10501
1       0.30    Premium     G     SI1  4.39  4.35  2.57   5.88   6.00    574
2       1.37      Ideal     F     VS1  7.28  7.22  4.32   5.96   5.70  11649
3       0.33       Fair     H    VVS2  4.40  4.32  2.84   6.51   5.90    922
4       0.32  Very Good     F     VS2  4.43  4.48  2.62   5.88   6.20    602
5       0.51    Premium     E     SI2  5.15  5.12  3.22   6.27   5.20   1205
6       1.50       Good     H     VS2  7.22  7.27  4.61   6.36   5.80  10291
7       0.85      Ideal     G     VS1  6.09  6.11  3.77   6.18   5.50   4373
8       0.33      Ideal     F     VS1  4.46  4.49  2.74   6.12   5.60    723
9       1.10      Ideal     G     VS1  6.69  6.65  4.09   6.13   5.40   6535
10      0.51  Very Good     E    VVS2  5.20  5.23  3.13   6.00   5.80   2365
11      0.54      Ideal     E     VS2  5.24  5.27  3.24   6.17   5.50   1754
12      1.51    Premium     G     VS2  7.20  7.31  4.55   6.27   5.80  12756
13      0.70    Premium     G     SI1  5.68  5.65  3.57   6.30   5.60   2386
14      0.74      Ideal     G    VVS2  5.90  5.88  3.58   6.07   5.60   3831
15      1.12    Premium     H     VS1  6.60  6.64  4.11   6.21   5.80   5845
16      2.02      Ideal     I     SI2  8.06  7.99  4.99   6.22   5.70  10412
17      0.90    Premium     D     SI1  6.15  6.11  3.84   6.26   5.80   4304
18      0.57      Ideal     D     VS2  5.35  5.42  3.30   6.13   5.60   2546
19      0.31  Very Good     I     SI1  4.32  4.30  2.73   6.33   5.30    523
20      0.51      Ideal     H     VS2  5.14  5.16  3.13   6.08   5.70   1442
21      0.30      Ideal     I     SI1  4.35  4.32  2.70   6.23   5.60    506
22      0.52      Ideal     F     VS2  5.22  5.19  3.19   6.13   5.70   1624
23      1.00       Good     H     SI2  6.25  6.33  4.02   6.39   5.50   3878
24      0.31      Ideal     G     SI1  4.36  4.40  2.70   6.16   5.60    627
25      0.30       Good     F     SI2  4.29  4.33  2.73   6.33   5.50    394
26      1.76    Premium     H     VS2  7.72  7.68  4.79   6.22   6.00  13626
27      0.36    Premium     H     VS2  4.60  4.55  2.79   6.10   6.00    729
28      1.21    Premium     H     VS2  6.82  6.78  4.18   6.15   5.80   6710
29      1.02      Ideal     E     SI2  6.46  6.52  4.00   6.16   5.50   4824
...      ...        ...   ...     ...   ...   ...   ...    ...    ...    ...
45819   0.56      Ideal     G     VS1  5.33  5.36  3.25   6.07   5.50   1855
45820   0.54      Ideal     G    VVS2  5.22  5.25  3.26   6.24   5.34   1962
45821   0.36      Ideal     F     VS2  4.61  4.58  2.80   6.09   5.70    932
45822   0.42      Ideal     G    VVS1  4.85  4.82  2.98   6.16   5.50   1235
45823   0.35    Premium     G     VS1  4.56  4.53  2.78   6.12   5.60    906
45824   0.71  Very Good     J     SI2  5.75  5.81  3.51   6.07   6.10   1805
45825   1.03      Ideal     F     VS2  6.43  6.45  4.01   6.23   5.60   7392
45826   0.31      Ideal     D     SI1  4.38  4.36  2.71   6.20   5.50    732
45827   0.61  Very Good     E     VS1  5.44  5.57  3.28   5.96   6.30   2025
45828   0.31      Ideal     H     VS2  4.38  4.41  2.68   6.10   5.70    507
45829   0.43      Ideal     E    VVS1  4.84  4.88  2.98   6.13   5.70   1433
45830   0.31    Premium     I     SI1  4.29  4.32  2.68   6.23   5.90    408
45831   1.13    Premium     G      I1  6.77  6.66  4.11   6.12   5.80   3746
45832   0.81  Very Good     E     SI2  5.91  5.99  3.71   6.24   5.70   2894
45833   0.53  Very Good     D     SI1  5.27  5.33  3.13   5.91   5.90   1415
45834   0.79       Good     I     SI1  5.85  5.80  3.72   6.39   5.50   2095
45835   0.81      Ideal     F     VS2  5.96  5.92  3.67   6.18   5.50   3624
45836   0.40       Good     H     VS2  4.82  4.75  2.84   5.94   6.40    945
45837   1.02    Premium     G     SI2  6.46  6.41  3.97   6.17   5.80   3027
45838   0.30      Ideal     E     VS2  4.34  4.30  2.67   6.18   5.60    844
458

In [61]:
#dummy coding(cut,color,clarity)
from sklearn.preprocessing import LabelEncoder
diamond_data = load_diamond_data()
diamond_data["depth"] = diamond_data["depth"] / 10
diamond_data["table"] = diamond_data["table"] / 10

enumValues = {"cut": {"Fair":0, "Good":1, "Very Good":2, "Premium":3, "Ideal":4},
              "color": {"J": 0, "I":1, "H":2, "G":3, "F":4, "E":5, "D":6},
              "clarity": {"I1":0, "SI2":1, "SI1":2, "VS2":3, "VS1":4,"VVS2":5, "VVS1":6, "IF":7}}
diamond_data.replace(enumValues, inplace=True)


In [31]:
# Cross Validation Setup
from sklearn.model_selection import ShuffleSplit
# Model seeds

# 0 :
# Linear Regression, Stochastic ...  
# 1 : ...

def generate_validation_sets(seed):
    shuffle = ShuffleSplit(n_splits=10, test_size=0.20, random_state=seed)
    return shuffle.split(diamond_data)

for train_index, validation_index in generate_validation_sets(0):
    print("%s %s" % (train_index, validation_index))
    

[ 3126  9324 44981 ... 42613 43567  2732] [12851 33212 27742 ...  9356 37933 43323]
[  811 25661  6887 ...  3083 28210 31900] [12634 43566 17212 ...  6465 21660 45776]
[26656 12191  8789 ... 36893   752 44222] [15297 35660 37577 ... 35868 27065 41071]
[40869 36220 25842 ... 21412  9036  2754] [41758 18030  1902 ... 12743  5666  2111]
[28426 17786  9548 ... 26903 12252  3271] [ 5498  4696 15041 ... 35010 19060  1915]
[12425  3979  6797 ...  4603 24796 27477] [36169 25287 25878 ...  8803 13650  1491]
[  915 25958 13091 ...  2938 33279 29233] [18311  8049 38022 ... 32370 30957 26543]
[44541 34249 39776 ...   259  9284 10056] [ 8195 18137  5031 ...  3632 37785 25227]
[32257  1579 35814 ...   251  5712 37854] [ 5241  4682 25597 ... 32290 28106 22695]
[36970 10043 19202 ... 45277  1017 22021] [15573 14193 15797 ...  7945 26934  8965]
36679 9170


In [92]:
# Normal Equation
import numpy as np

X = np.array(diamond_data)

X = np.delete(X, -1, axis=1)

X = np.c_[np.ones((len(X), 1)),X]

y = diamond_data["price"]

def theta(X, y):

    transpose = X.T

    mult1 = transpose.dot(X)

    try:
        inverse = np.linalg.inv(mult1)

    except np.linalg.LinAlgError:
        print("Not invertible")
        return np.zeros(1,1)

    else:
        mult2 = (inverse.dot(transpose)).dot(y)
        return mult2

print(theta(X, y))

[ 4.48161979e+03  1.08245982e+04  1.13666370e+02  3.23386040e+02
  5.02144216e+02 -9.31422638e+02  4.73144283e+01 -4.00443256e+00
 -8.48290762e+02 -3.18265497e+02]
